apiVersion: apps/v1
kind: Deployment
metadata:
    name: lobsters-www
spec:
  selector:
    matchLabels:
      app: lobsters-www
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lobsters-www
    spec:
      containers:
        - name: lobsters
          image: meyersh/lobsters:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: database-url
