apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lobsters-mysql
  name: lobsters-mysql
spec:
  selector:
    matchLabels:
      app: lobsters-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: lobsters-mysql
      name: lobsters-mysql
    spec:

      containers:
        - name: mysql
          image: mysql:5.6.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: mysql-password
            - name: MYSQL_USER
              value: lobsters
            - name: MYSQL_DATABASE
              value: lobsters
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      volumes:
        - name: "mysql"
          persistentVolumeClaim:
            claimName: lobsters-mysql
